/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Script {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'description' : string,
  'author' : Principal,
  'updatedAt' : bigint,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createScript' : ActorMethod<[string, string, string, string], string>,
  'deleteScript' : ActorMethod<[string], undefined>,
  'filterScriptsByCategory' : ActorMethod<[string], Array<Script>>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScript' : ActorMethod<[string], Script>,
  'getScriptsByAuthor' : ActorMethod<[Principal], Array<Script>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchScriptsByTitle' : ActorMethod<[string], Array<Script>>,
  'updateScript' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];